---

detectors:
  Attribute:
    exclude:
      - IntegrationTestsRails::Configuration

  FeatureEnvy:
    exclude:
      - IntegrationTestsRails::Capybara::Dsl#retry_on_fail

  LongParameterList:
    max_params: 5

  TooManyStatements:
    max_statements: 15

  TooManyInstanceVariables:
    exclude:
      - IntegrationTestsRails::Configuration

  UncommunicativeVariableName:
    accept:
      - e
